#!/bin/bash

set -e
set -o nounset

DEST_DIR=~/.local/share/nvim/site/pack/packer/start/packer.nvim
VERSION=dac4088c70f4337c6c40d1a2751266a324765797

ARCHIVE_URL=https://github.com/wbthomason/packer.nvim/archive/$VERSION.tar.gz

set -x

rm -rf ${DEST_DIR}
mkdir -p ${DEST_DIR}

cd ${DEST_DIR}
curl -L -s $ARCHIVE_URL | tar xvz --strip-components 1
