#!/bin/bash

set -e
set -o nounset

if [ "$(uname -s)" != "Linux" ]; then
  echo 'Use config/brewfile to install neovim here!'
  exit
fi

if which nvim >/dev/null; then
  v="$(nvim --version | head -n 1 | cut -d v -f 2)"
  maj="$(echo "$v" | cut -d . -f 1)"
  min="$(echo "$v" | cut -d . -f 2)"
  if [ "$maj" -gt 0 ] || [ "$min" -gt 10 ]; then
    echo 'Neovim is already installed, not going to install it again.'
    nvim --version | head -n 1
    exit 0
  fi
fi

start_dir="$(pwd -P)"
echo $start_dir
curl -LO https://github.com/neovim/neovim/releases/download/v0.10.4/nvim-linux-x86_64.appimage
sha256sum -c <<X
d1b1488ef6a970dc3a2826b788d31d81b2f308ad42ef70ed62d35d0bf6189336  nvim-linux-x86_64.appimage
X
mv nvim-linux-x86_64.appimage nvim.appimage
chmod u+x nvim.appimage

cd /
sudo "${start_dir}/nvim.appimage" --appimage-extract
rm -f "${start_dir}/nvim.appimage"
sudo mv squashfs-root neovim-root

cd "${HOME}"
rm -f .bin/nvim
ln -s /neovim-root/AppRun .bin/nvim

cd "${start_dir}"
