#!/bin/bash

set -e

URL=https://github.com/spraints/t
LOCAL=${HOME}/src/github.com/spraints/t

if ! which cargo >&/dev/null; then
  source "$HOME/.cargo/env"
fi

if [[ ! -d "${LOCAL}" ]]; then
  git clone "$URL" "$LOCAL"
fi

cd "$LOCAL"
make install
