#!/bin/bash

set -e
set -o nounset

root="$(cd "$(dirname $0)"; pwd -P)"
ts=$(date +%s)

linkup() {
  local f="$1"
  local src="${root}/${f}"
  local dst="${HOME}/.ssh/${f}"
  if [ ! -e "$dst" ]; then
    (set -x; ln -s "$src" "$dst")
  elif [ "$(readlink "$dst")" != "$src" ]; then
    (set -x; mv "$dst" "$dst.bak.$ts"; ln -s "$src" "$dst")
  else
    echo $dst already exists
  fi
}

linkup authorized_keys
linkup config
touch ${root}/config.local
linkup config.local

echo set up .ssh/sockets
mkdir -p "${HOME}/.ssh/sockets"
chmod 700 "${HOME}/.ssh/sockets"
