#!/bin/bash

echo "Allowing $USER to run anything with sudo."
root="$(cd "$(dirname $0)"; pwd -P)"
sudo env EDITOR=${root}/edit-sudoers AUTH_USER=$USER \
  visudo -f /etc/sudoers.d/spraints-dotfiles-dev-vm
