#!/bin/bash
#/ Usage: script/install-laptop [--work|--personal]

set -e
set -o nounset

cd $(dirname "$0")/..
set -x
script/install-dotfiles
script/install-config config/strap-like # needs to go before brewfile, maybe also sudoers
script/install-config config/sudoers
script/install-config config/gnupg
script/install-config config/ssh
script/install-config config/brewfile
script/install-config config/neovim-packer
script/install-config config/macos

if $work; then
  script/install-config config/xbar
fi
