#!/bin/bash
#/ Usage: script/install-laptop [--work|--personal]

set -e
set -o nounset

work=false
personal=false
case "${1:-}" in
  --work)
    work=true
    ;;
  --personal)
    personal=true
    ;;
  *)
    cat "$0" | grep ^#/ | cut -c4-
    exit 1 ;;
esac


cd $(dirname "$0")/..
set -x
script/install-dotfiles
script/install-config config/strap-like # needs to go before brewfile, maybe also sudoers
script/install-config config/sudoers
script/install-config config/ssh
script/install-config config/brewfile
script/install-config config/neovim-packer
script/install-config config/macos
script/install-config config/rustup
script/install-config config/fancy-prompt

if $work; then
  # todo - install xbar for personal, too, except 't'.
  # todo - make this work on a fresh machine. currently it fails because of cloning a private github repo.
  script/install-config config/xbar
fi
