#!/bin/bash

set -ex

script/install-dotfiles

# Codespaces has some opinionated git config that we need to use.
ln -s .gitconfig.orig ${HOME}/.gitconfig.local

sudo apt-get install -y \
  silversearcher-ag \
  tmux

# Do this last. If it fails, I'd rather have the other parts done.
config/nvim/install
config/neovim-packer/install
