#!/bin/bash

set -ex

script/install-dotfiles

sudo apt-get install -y \
  silversearcher-ag \
  tmux

# Do this last. If it fails, I'd rather have the other parts done.
config/nvim/install
config/neovim-packer/install
config/codespaces/install
