#!/bin/bash

set -e

script/install-dotfiles
script/install-config config/nvim
script/install-config config/neovim-packer

cat > ~/.gitconfig.local <<GITCONFIG
[url "git@github.com:"]
	insteadOf = https://github.com/
[url "git@ghe.io:"]
	insteadOf = https://ghe.io/
GITCONFIG
