# Matt's set of basic packages.

# Then, you can cd here and do this:
#    brew bundle

tap "homebrew/cask-fonts"

# useful stuff for my programming hobby
brew "gh"
brew "iterm2"
brew "jq"
brew "moreutils" # particularly for the `ts` command
brew "mtr"
brew "neovim"
brew "pstree"
brew "rbenv"
brew "ruby-build"
brew "rustup-init"
brew "tcptrace"
brew "the_silver_searcher" # ag, ack replacement
brew "tmux"
brew "watch"

# personal apps that I use (comment these out on work computer)
brew "gnucash"
brew "handbrake"
brew "keepassxc"
brew "ledger"
brew "yt-dlp"

# Things I might want to use homebrew to install, but might not.
#cask "firefox"
#cask "google-chrome"
#cask "keybase"
#cask "spotify"
#cask "virtualbox"
#cask "viscosity"
#cask "visual-studio-code"

# fonts
cask "font-fira-mono-nerd-font"
