#!/bin/bash

set -e
set -o nounset

root="$(cd "$(dirname $0)"; pwd -P)"

sudo mkdir -p -m 755 /etc/apt/keyrings
sudo cp "${root}/githubcli-archive-keyring.gpg" \
  /etc/apt/keyrings/githubcli-archive-keyring.gpg
sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
  | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

sudo apt update
sudo apt install gh -y
